title: I AM IT
description: > # this means to ignore newlines until "baseurl:"
  Description for the website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iamit.com" # the base hostname & protocol for your site

#Information that is used to create the Terms of Service & Privacy Policy pages
company: I AM IT
location: Iowa

# Build settings
markdown: kramdown
exclude: [node_modules]
include: [_pages]
permalink: /posts/:title/

# Collections
collections:
    - app-design
    - data-management
    - client-relations
    - programming
    - infrastructure
    - leadership
    - product-dev
    - security
